### ISSUE TITLE
关于之前有一个崛起改狱泉乡的一个脚本问题

### ISSUE THREAD

**Issue by eatureide** [dtlnor/MHRTextDump#1]
我尝试将map改为11（龙宫古城）但是进去后就闪退了，可能是什么原因？你的仓库好像没有这个脚本，所以在这里提问了，谢谢

**Comment by dtlnor** [comment]
~~因为跟fix_spawn_area脚本冲突了估计~~
哦哦哦你改了我腳本啊。龙宫古城是因为没有怪物出生的数据。有很多怪没有设置这个地图的出生点，所以就会爆炸。

**Comment by dtlnor** [comment]
一般来说他找不到对应的出生点就会去找第一个数据（比如找不到メイン就会找第一个（可能是A这样））。但如果根本没有那个地图的init set数据可能就会寄。你要么在每个怪的initset.user数据里面加一条数据（这个可能比较难），要么就把其中一条数据对应的地图给改掉（这个比较容易）。

**Comment by dtlnor** [comment]
这也是为什么我没有添加龙宫古城的选项（）

**Comment by eatureide** [comment]
要么就把其中一条数据对应的地图给改掉？你指的是QuestDataDump.json吗？
lua不是很会玩

**Comment by eatureide** [comment]
天慧龙有龙宫城的出生数据，但是它的出生点是在洞口里，是否修改对应的QuestDataDump.json成员就能修改出生地呢？

**Comment by dtlnor** [comment]
> 要么就把其中一条数据对应的地图给改掉？你指的是QuestDataDump.json吗？ lua不是很会玩

并不是哦，你要改数据有两个方法，一个是ref用脚本改（这个比较难但比较优雅）。一个是解包改数据再封包（就是类似我的强制出生地点mod一样）。把boss init set文件里面的map类型block类型改掉就可以了。（虽然添加会更好，但rsz这该死的结构估计一般人搞不定加数据）

**Comment by dtlnor** [comment]
> 天慧龙有龙宫城的出生数据，但是它的出生点是在洞口里，是否修改对应的QuestDataDump.json成员就能修改出生地呢？

不，因为questdatadump是用来给我恢复原样用的，apply mod的时候会覆写设置（比如出生地点强制为main（メイン））。同樣，這時候建議你改boss init set文件

**Comment by dtlnor** [comment]
Assume fixed
